#! /usr/bin/env bash

printf '\n\nStarting the environment!\n\n'

until $(curl -o /dev/null -s -I -f http://localhost:3000); do
    printf '.'
    sleep 1
done

printf '\n\nThe environment is started!\n\n'