#! /usr/bin/env bash

printf '\n\nPreparing the environment!\n\n'

until $(curl -o /dev/null -s -I -f http://localhost:3000); do
    printf '.'
    sleep 2
done

printf '\n\nThe environment is prepared!\n\n'